services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_app
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    container_name: dashboard_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
