services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_app
    volumes:
      - .:/var/www
    depends_on:
      - sqlsrv

  nginx:
    image: nginx:alpine
    container_name: dashboard_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlsrv
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"